### ISSUE TITLE
V0.4 - Error in console : "GetData is not defined"

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/magnificPopup#1]
The new version 0.4 throws an error, and doesn't work on V2.16 p202003201134 : GetData is not defined.

V0.3 is ok on a 2.16.

**Comment by franck-paul** [comment]
Est-ce que le thème utilisé charge bien util.js ?

**Comment by franck-tomek** [comment]
Yep, ça semble ça, je regarde comment c'est inséré dans le thème par défaut.

**Comment by franck-tomek** [comment]
Bon, en fait c'est dans le contexte home que ça ne fonctionne pas. En post c'est ok.

**Comment by franck-paul** [comment]
En fait oui, va falloir que je remonte l'inclusion de util.js dans le layout des templates, histoire d'être tranquille.

On fera un truc un peu plus chiadé pour la 2.17, en prévoyant par exemple qu'un plugin puisse indiquer qu'il en a besoin.

**Comment by franck-tomek** [comment]
OK, du coup je sais ce que je dois modifier. Le plus logique est de le mettre dans le _head.html non ?

**Comment by franck-paul** [comment]
Je laisse ouvert pour la prochaine version qui tiendra compte du mécanisme qui sera mis en place pour la 2.17, histoire d'éviter si possible d'inclure du javascript quand c'est pas utile.
