### ISSUE TITLE
Pas de légende et pas d'animation

### ISSUE THREAD

**Issue by Pedrofsky** [franck-paul/magnificPopup#2]
Bonjour Franck,
J'ai installé et activé le plugin sur [mon site](https://www.videogiciels.fr/?post/2022/11/09/Assassin-s-Creed-%3A-Liberation-Remastered-%28PS4%29).
Mais par rapport aux exemples de [cette page](https://dimsemenov.com/plugins/magnific-popup/), je n'ai pas de légende qui s'affiche sous l'image (au contraire de l'image de l'hippopotame), et je n'ai pas non plus d'animation de zoom ou dézoom en entrant ou sortant de l'image (au contraire de l'image du troupeau d'animaux cornus).
Je suis en Dotclear 2.23.1. J'utilise un thème Japonisant modifié, [dispo ici](http://pvg.free.fr/tmp/dc2/theme-japonisant-1.3.zip).
Savez-vous comment puis-je faire pour que les descriptions d'image s'affichent bien en légende, et pour activer la jolie animation quand on clique sur l'image ?

**Comment by franck-paul** [comment]
Je crois que ce plugin récupère le contenu de l'attribut `title` du lien (balise `<a href="..." title="…">…` vers l'image complète pour l'afficher comme légende et il n'y en a pas sur les vôtres.

**Comment by Pedrofsky** [comment]
> Je crois que ce plugin récupère le contenu de l'attribut `title` du lien (balise `<a href="..." title="…">…` vers l'image complète pour l'afficher comme légende et il n'y en a pas sur les vôtres.

Pourtant j'ajoute les images via le sélecteur de média dans mon article, en sélectionnant bien "légende et titre". Voici la source d'une des images avec sa légende, dans mon article :

```
<figure style="margin: 0 auto; display: table;"><a class="media-link" href="/blog219custom/public/ass_creed_liberation/tomb_raider.jpg"><img alt="tomb raider.jpg, nov. 2022" class="media" src="/blog219custom/public/ass_creed_liberation/.tomb_raider_m.jpg" /></a>

<figcaption>Au Mexique, quelques séquences de chasse au trésor avec grimpette assistée qui font beaucoup penser à <u>Indiana Jones</u>, <u>Uncharted</u> et aux récents <u>Tomb Raider</u>.</figcaption>
</figure>
```

Par ailleurs j'ai fait un test et oui je vous confirme que si j'ajoute l'attribut title, à la main, dans la source de mon article, cela fonctionne bien. Mais comment faire pour que cet attribut soit alimenté en automatique lorsque j'ajoute des images ? Existe-t-il une autre méthode pour ajouter des images ?

**Comment by franck-paul** [comment]
Quel syntaxe et quel éditeur est utilisé pour l'insertion d'image ?

**Comment by Pedrofsky** [comment]
> Quel syntaxe et quel éditeur est utilisé pour l'insertion d'image ?

Pour moi j'utilise le paramétrage par défaut de Dotclear 2.23.1 à ce niveau. Pour essayer de vous répondre de façon plus précise, je vois que le plugin dcCKEditor est activé.

Voici des captures d'écran de l'éditeur. Si jamais cela ne répond pas à votre question, dites-moi comment je peux vérifier ces infos ?

[Capture 1](https://videogiciels.fr/public/sshot-268.png)
[Capture 2](https://videogiciels.fr/public/sshot-267.png)

Je précise que j'insère les images avec le bouton "sélecteur de médias".

**Comment by franck-paul** [comment]
Le problème vient en fait de l'insertion d'image avec CKEditor, ça sera corrigé dans la prochaine 2.24 de Dotclear.

En attendant il faudra compléter l'attribut `title="…"` des liens, en basculant en mode source.

**Comment by Pedrofsky** [comment]
Merci !
