### ISSUE TITLE
Pas d'animation

### ISSUE THREAD

**Issue by Pedrofsky** [franck-paul/magnificPopup#3]
Bonjour Franck,
J'ai installé et activé le plugin sur [mon site](https://www.videogiciels.fr/?post/2022/11/09/Assassin-s-Creed-%3A-Liberation-Remastered-%28PS4%29).
Mais par rapport aux exemples de [cette page](https://dimsemenov.com/plugins/magnific-popup/), je n'ai pas d'animation en entrant ou sortant de l'image (par exemple la 3ème image avec le troupeau d'animaux cornus).
Je trouve cette animation très élégante et j'aimerais l'utiliser sur mon site.
Je suis en Dotclear 2.23.1. J'utilise un thème Japonisant modifié, [dispo ici](http://pvg.free.fr/tmp/dc2/theme-japonisant-1.3.zip).
Comment puis-je faire pour activer l'animation une fois le plugin installé ?

**Comment by franck-paul** [comment]
Bonjour,

Pour ça il faudrait modifier le plugin pour qu'il puisse le permettre ou a minima rajouter les CSS de transition correspondantes dans la feuille de style du thème.

**Comment by Pedrofsky** [comment]
J'ai ajouté ce qui suit au fichier style.css de mon thème mais pas de changement, sans doute la modification du plugin est-elle obligatoire ?

```
/* overlay at start */
.mfp-fade.mfp-bg {
  opacity: 0;

  -webkit-transition: all 0.15s ease-out;
  -moz-transition: all 0.15s ease-out;
  transition: all 0.15s ease-out;
}
/* overlay animate in */
.mfp-fade.mfp-bg.mfp-ready {
  opacity: 0.8;
}
/* overlay animate out */
.mfp-fade.mfp-bg.mfp-removing {
  opacity: 0;
}

/* content at start */
.mfp-fade.mfp-wrap .mfp-content {
  opacity: 0;

  -webkit-transition: all 0.15s ease-out;
  -moz-transition: all 0.15s ease-out;
  transition: all 0.15s ease-out;
}
/* content animate it */
.mfp-fade.mfp-wrap.mfp-ready .mfp-content {
  opacity: 1;
}
/* content animate out */
.mfp-fade.mfp-wrap.mfp-removing .mfp-content {
  opacity: 0;
}
```

**Comment by Pedrofsky** [comment]
Bonjour Franck,
J'ai trouvé la solution :-)
C'est qu'il faut modifier public.js avec les instructions ci-dessous :

```
// Initialize popup as usual
$('.popup-link').magnificPopup({
  // Delay in milliseconds before popup is removed
  removalDelay: 300,

  // Class that is added to popup wrapper and background
  // make it unique to apply your CSS animations just to this exact popup
  mainClass: 'mfp-fade'
});
```

**Comment by franck-paul** [comment]
Je vais rouvrir ce ticket pour voir comment intégrer ça dans une future version.
